apiVersion: apps/v1
kind: Deployment
metadata:
  name: hackathon-report
  namespace: hostwo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hackathon-report
  template:
    metadata:
      labels:
        app: hackathon-report
    spec:
      nodeSelector:
        kubernetes.io/arch: arm64
      containers:
      - name: hackathon-report
        image: 222829864634.dkr.ecr.ap-southeast-1.amazonaws.com/duckchain-report:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

---
apiVersion: v1
kind: Service
metadata:
  name: hackathon-report-service
  namespace: hostwo
spec:
  selector:
    app: hackathon-report
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hackathon-report-ingress
  namespace: hostwo
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP":80}]'
spec:
  ingressClassName: alb
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: hackathon-report-service
            port:
              number: 80
