apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: convertx-pvc
  namespace: convertx
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 30Gi  # 临时文件存储
