# GPU NodePool 配置
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: nodepool-gpu
spec:
  # 模板配置
  template:
    metadata:
      labels:
        node-type: gpu
        workload-type: ml
    spec:
      # 节点类别配置
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: nodeclass-gpu
      
      # 污点配置 - 确保只有 GPU 工作负载调度到这些节点
      taints:
        - key: nvidia.com/gpu
          value: "true"
          effect: NoSchedule
      
      # 资源要求
      requirements:
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: 
            # 测试用 g4dn.xlarge (ap-southeast-1 可用)
            - g4dn.xlarge    # 1x NVIDIA T4, 4 vCPU, 16 GB RAM, 125GB NVMe
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
  
  # 扩展限制
  limits:
    cpu: 1000
    memory: 1000Gi
  
  # 节点终止策略
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s

---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: nodeclass-gpu
spec:
  # AMI 配置 - 使用 AL2023 EKS-optimized NVIDIA AMI
  amiFamily: AL2023
  amiSelectorTerms:
    - name: "amazon-eks-node-al2023-x86_64-nvidia-1.33-*"
      owner: "amazon"
  
  # 实例配置 - 本地 NVMe 存储策略
  instanceStorePolicy: RAID0  # 仅对本地 NVMe 设备做 RAID0
  
  # 用户数据 - AL2023 优化配置 + 本地存储挂载
  userData: |
    #!/bin/bash
    /usr/bin/nodeadm init --cluster-name eks-karpenter-env
    
    # 确保 kubelet 服务启动
    systemctl enable kubelet
    systemctl start kubelet
    
    # Configure local NVMe storage mount point
    mkdir -p /mnt/nvme-cache
    
    # Check for local NVMe storage (RAID0 configured by Karpenter)
    if [ -b /dev/nvme1n1 ]; then
        # Format and mount local storage for cache
        mkfs.ext4 /dev/nvme1n1
        mount /dev/nvme1n1 /mnt/nvme-cache
        chmod 777 /mnt/nvme-cache
        
        # Add to fstab for auto-mount after reboot
        echo "/dev/nvme1n1 /mnt/nvme-cache ext4 defaults,nofail 0 2" >> /etc/fstab
        
        # Create Kubernetes local storage directory
        mkdir -p /mnt/nvme-cache/k8s-local-storage
        chmod 777 /mnt/nvme-cache/k8s-local-storage
    fi
  
  # 安全组和子网
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-karpenter-env"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-karpenter-env"
  
  # IAM 角色
  role: "KarpenterNodeInstanceRole-eks-karpenter-env"
  
  # 块设备映射 - 为 ML 工作负载提供足够存储
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi  # 持久化卷存储空间
        volumeType: gp3
        iops: 3000
        throughput: 125
        deleteOnTermination: true
