apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: firecrawl-nuq-postgres-pvc
  namespace: firecrawl
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp3
  resources:
    requests:
      storage: 10Gi
