# AMD64 NodePool - Intel 兼容性
apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: nodepool-amd64
spec:
  weight: 50  # 较低优先级 - 兼容性需求时使用
  template:
    metadata:
      labels:
        node-type: "amd64"
        arch: "amd64"
        cost-tier: "standard"
    spec:
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: nodeclass-amd64
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]  # Spot 优先
        - key: node.kubernetes.io/instance-type
          operator: In
          values: 
            # Intel 第4代 (M7i) - 高性能
            - m7i.large
            - m7i.xlarge
            - m7i.2xlarge
            - m7i.4xlarge
            # 计算优化 Intel (C7i)
            - c7i.large
            - c7i.xlarge
            - c7i.2xlarge
            - c7i.4xlarge
        - key: topology.kubernetes.io/zone
          operator: In
          values: ["ap-southeast-1a", "ap-southeast-1b", "ap-southeast-1c"]
  limits:
    cpu: 500
    memory: 500Gi
  disruption:
    consolidationPolicy: WhenEmptyOrUnderutilized
    consolidateAfter: 30s

---
# AMD64 NodeClass
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: nodeclass-amd64
spec:
  # 使用 Amazon Linux 2023
  amiFamily: AL2023
  amiSelectorTerms:
    - name: "amazon-eks-node-al2023-x86_64-standard-1.33-*"
  
  instanceStorePolicy: RAID0
  userData: |
    #!/bin/bash
    /usr/bin/nodeadm init --cluster-name eks-karpenter-env
    
  # 子网和安全组使用 karpenter.sh/discovery 标签
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-karpenter-env"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "eks-karpenter-env"
  
  instanceProfile: "KarpenterNodeInstanceProfile-eks-karpenter-env"
  
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 100Gi
        volumeType: gp3
        deleteOnTermination: true
