apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-portainer
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0123456789abcdef0  # EKS Karpenter 集群的 EFS ID
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/portainer"
volumeBindingMode: Immediate
allowVolumeExpansion: false
