apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-portainer
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-xxxxxxxxxxxxxxxxx   # 替换为你的 EFS 文件系统 ID
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/portainer"
