apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# 统一 namespace。若需改用其他 namespace，改这一处即可
# （注意：Pod Identity 关联也须使用相同 namespace）
namespace: logging

resources:
  - logging-namespace.yaml
  - loki-config.yaml
  - loki-deployment.yaml
  - loki-ingress.yaml
  - alloy-config.yaml
  - alloy-daemonset.yaml
